//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODULE
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public int Credit { get; set; }
        public decimal ClassPerHour { get; set; }
        public int Weeks { get; set; }
        public decimal Used_hours { get; set; }
        public decimal Self_study { get; set; }
        public decimal Remaining_Hours { get; set; }
    }
}
